Users/urls.py
from django.urls import path
from .views import signup,signUpBtnClick,save_food_data,user_list,save_activity_data,view_user_data,view_date_data,delete_user

urlpatterns = [
    path('', signup, name='signup'),
    path('userList/', user_list, name='user_list'),
    path('signUpBtnClick/', signUpBtnClick, name='signUpBtnClick'),
    path('save_food_data/', save_food_data, name='save_food_data'),
    path('save_activity_data/', save_activity_data, name='save_activity_data'),
    path('userList/view_user_data/<int:id>', view_user_data, name='view_user_data'),
    path('view_date_data/', view_date_data, name='view_date_data'),
    path('delete-user/', delete_user, name='delete_user'),
    ]

calorie_tracker_python/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Users.urls')),

]

Users/models.py
from django.db import models

class User(models.Model):
    name = models.CharField(max_length=100)
    weight = models.FloatField()
    height = models.FloatField()
    sex = models.CharField(max_length=10)
    age = models.PositiveIntegerField()  # Field to store age
    bmr = models.FloatField(null=True, blank=True) 

    def save(self, *args, **kwargs):
        print(f"Weight: {self.weight}, Height: {self.height}, Age: {self.age}")  # Add this line
        if self.sex.lower() == 'male':
            self.bmr = round(66.4730 + (13.7516 * float(self.weight)) + (5.0033 * float(self.height)) - (6.7550 * float(self.age)), 2)
        elif self.sex.lower() == 'female':
            self.bmr =round( 655.0955 + (9.5634 * float(self.weight)) + (1.8496 * float(self.height)) - (4.6756 * float(self.age)), 2)
        super().save(*args, **kwargs)



class FoodData(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    food = models.CharField(max_length=100)
    date = models.DateField()
    food_group = models.CharField(max_length=50)
    meal_type = models.CharField(max_length=50)
    serving = models.FloatField()
    calorie = models.FloatField()  # New field for calorie per serving
    calorie_in = models.FloatField(blank=True, null=True)  # Allow null initially

    def save(self, *args, **kwargs):
        self.calorie_in = float(self.serving) * float(self.calorie)
        print(self.calorie_in, self.calorie , self.food)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.user.name}'s {self.food} on {self.date}"
    


class ActivityData(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    activity_name = models.CharField(max_length=255)
    date = models.DateField()
    activity_description = models.CharField(max_length=2000)
    met_value = models.FloatField()
    duration = models.FloatField()
    calorie_out = models.FloatField(blank=True, null=True)  
    def save(self, *args, **kwargs):
        duration_hours = float(self.duration) / 60.0
        user_weight_kg = float(self.user.weight) 
        self.calorie_out = round(float(self.met_value) * float(user_weight_kg) * float(duration_hours), 2)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.user.name}'s {self.activity_description} on {self.date}"

Users/views.py
from datetime import datetime
from django.shortcuts import get_object_or_404, render,redirect
from django.http import HttpResponse
from django.template import loader
from .models import User,FoodData,ActivityData
from django.views.decorators.csrf import csrf_protect
from django.http import JsonResponse
from django.contrib import messages
import Users
from django.db.models import Sum
from django.contrib.sessions.models import Session
from django.core import serializers
from django.utils import timezone

def signup(request):
    template = loader.get_template('sign-up.html')
    return HttpResponse(template.render())


def user_list(request):
    users = User.objects.all()
    return render(request, 'user-list.html', {'users': users})


def signUpBtnClick(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        weight = request.POST.get('weight')
        height = request.POST.get('height')
        gender = request.POST.get('gender')
        age = request.POST.get('age')
        
        user = User.objects.create(
            name=name,
            weight=weight,
            height=height,
            sex=gender,
            age=age
        )
        return redirect('user_list')
    else:
        return render(request, 'sign-up.html')
    

def save_food_data(request):
    if request.method == 'POST':
        user_id = request.POST.get('user_id')  
        food = request.POST.get("food")
        date = request.POST.get("date")
        food_group = request.POST.get("food_group")
        meal_type = request.POST.get("meal_type")
        serving = request.POST.get("serving")
        calorie = request.POST.get("calorie")

        user = User.objects.get(id=user_id)

        foodData = FoodData.objects.create(
            user=user,                   
            food=food,
            date=date,
            food_group=food_group,
            meal_type=meal_type,
            serving=serving,
            calorie=calorie,
        )
        return redirect(request.META.get('HTTP_REFERER', 'user'))
    return redirect(request.META.get('HTTP_REFERER', 'user'))


def save_activity_data(request):
    if request.method == 'POST':
        user_id = request.POST.get('user_id')  
        activityName = request.POST.get("activityName")
        date = request.POST.get("date")
        activityDescription = request.POST.get("activityDescription")
        metValue = request.POST.get("metValue")
        duration = request.POST.get("duration")

        user = User.objects.get(id=user_id)

        activityData = ActivityData.objects.create(
            user = user,
            activity_name = activityName,
            date = date,
            activity_description = activityDescription,
            met_value = metValue,
            duration = duration
        )
        return redirect(request.META.get('HTTP_REFERER', 'user'))   
    else:
        form = FoodForm()
    return render(request, 'your_template.html', {'form': form})


def view_user_data(request,id):
    user = User.objects.get(id=id)


    
    food_data = FoodData.objects.filter(user=user)
    activity_data = ActivityData.objects.filter(user=user)

        
    food_data_by_date = food_data.values('date').annotate(total_calorie_in=Sum('calorie_in'))
    activity_data_by_date = activity_data.values('date').annotate(total_calorie_out=Sum('calorie_out'))

       
    data_by_date = {}
    for entry in food_data_by_date:
        date = entry['date']
        data_by_date[date] = {'date': date, 'calorie_in': entry['total_calorie_in']}

    for entry in activity_data_by_date:
        date = entry['date']
        if date in data_by_date:
            data_by_date[date]['calorie_out'] = entry['total_calorie_out']
        else:
             data_by_date[date] = {'date': date, 'calorie_out': entry['total_calorie_out']}

       
    user_bmr = User.objects.get(id=id).bmr
    user_name = User.objects.get(id=id).name


       
    for date, data in data_by_date.items():
         data['calorie_in'] = data.get('calorie_in', 0)  
         data['calorie_out'] = data.get('calorie_out', 0)
         data['net_calorie'] = data['calorie_in'] - user_bmr - data['calorie_out']
         data['bmr'] = user_bmr
         print(date)

        
    return render(request, 'view-user-data.html',{'data_by_date': data_by_date,'user':user})
  
def view_date_data(request):
    selected_date = None
    user = None

    if request.method == 'POST':
        selected_date_str = request.POST.get('selected_date')
        user_id = request.POST.get('user_id')

        print(user_id)
        user = User.objects.get(id=user_id)

        selected_date = datetime.strptime(selected_date_str, '%B %d, %Y').date()
        food_data = FoodData.objects.filter(user=user, date=selected_date)
        activity_data = ActivityData.objects.filter(user=user, date=selected_date)
        calorie_in_sum = food_data.aggregate(total_calorie_in=Sum('calorie_in'))['total_calorie_in']
        calorie_out_sum = activity_data.aggregate(total_calorie_out=Sum('calorie_out'))['total_calorie_out']
        if calorie_in_sum is None:
            calorie_in_sum = 0  
        if calorie_out_sum is None:
            calorie_out_sum = 0 

        net_calorie = calorie_in_sum - user.bmr - calorie_out_sum

     
        selected_date_str = selected_date.strftime('%Y-%m-%d')

       
        request.session['selected_date'] = selected_date_str
        request.session['user_id'] = user_id 

    elif request.method == 'GET':  
        selected_date_str = request.GET.get('selected_date')
        if selected_date_str:
            selected_date = timezone.datetime.strptime(selected_date_str, '%Y-%m-%d').date()
            user_id = request.GET.get('user_id')  
            user = User.objects.get(id=user_id)
            food_data = FoodData.objects.filter(user=user, date=selected_date)
            activity_data = ActivityData.objects.filter(user=user, date=selected_date)
            calorie_in_sum = food_data.aggregate(total_calorie_in=Sum('calorie_in'))['total_calorie_in']
            calorie_out_sum = activity_data.aggregate(total_calorie_out=Sum('calorie_out'))['total_calorie_out']
            if calorie_in_sum is None:
                calorie_in_sum = 0  
            if calorie_out_sum is None:
                calorie_out_sum = 0 
            
            net_calorie = calorie_in_sum - user.bmr - calorie_out_sum

            
            request.session['selected_date'] = selected_date_str
            request.session['user_id'] = user_id  

    elif 'selected_date' in request.session:
        selected_date_str = request.session['selected_date']
        selected_date = timezone.datetime.strptime(selected_date_str, '%Y-%m-%d').date()
        user_id = request.session['user_id']  
        user = User.objects.get(id=user_id)
        food_data = FoodData.objects.filter(user=user, date=selected_date)
        activity_data = ActivityData.objects.filter(user=user, date=selected_date)
        calorie_in_sum = food_data.aggregate(total_calorie_in=Sum('calorie_in'))['total_calorie_in']
        calorie_out_sum = activity_data.aggregate(total_calorie_out=Sum('calorie_out'))['total_calorie_out']
        if calorie_in_sum is None:
            calorie_in_sum = 0  
        if calorie_out_sum is None:
            calorie_out_sum = 0 
        
        net_calorie = calorie_in_sum - user.bmr - calorie_out_sum


    print(activity_data)

    return render(request, 'view-date-data.html', {'food_data': food_data, 'selectedDate': selected_date , 'activity_data': activity_data, 'user': user, 'calorieIn': calorie_in_sum, 'calorieOut': calorie_out_sum, 'netCalorie': net_calorie })


def delete_user(request):
    if request.method == 'POST':
        user_id = request.POST.get('user_id')
        user = get_object_or_404(User, id=user_id)
        user.delete()
        return redirect('user_list')
    else:
        return redirect('user_list')

Users/templates/activity-food-popup.html
<div class="modal fade" id="addDataModal" tabindex="-1" aria-labelledby="addDataModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content add-data-modal">
            <div class="modal-header">
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item" role="presentation">
                        <a class="nav-link active" id="food-tab" data-toggle="tab" href="#food" role="tab"
                            aria-controls="food" aria-selected="true">Add Food</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a class="nav-link" id="activity-tab" data-toggle="tab" href="#activity" role="tab"
                            aria-controls="activity" aria-selected="false">Add Activity</a>
                    </li>
                </ul>
            </div>
            <div class="modal-body">
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active" id="food" role="tabpanel" aria-labelledby="food-tab">
                        <form method="post" action="{% url 'save_food_data' %}">
                            {% csrf_token %}
                            <div class="input-field">
                                <label>Select Date</label>
                                <input type="date" id="date" name="date" value="06/24/2022" placeholder="Age"
                                    autocomplete="off" required>
                            </div>

                            <div class="input-field">
                                <label for="foodInput">Search and Select Food</label>
                                <div>
                                    <input type="text" name="food" id="foodInput" placeholder="Type to search..."
                                        autocomplete="off" required>
                                    <div class="dropdown-content" id="searchResults">

                                    </div>
                                </div>
                            </div>
                            <div class="input-field">
                                <label>Select Meal Type</label>
                                <select name="meal_type" class="selectbox">
                                    <option>Breakfast</option>
                                    <option>Lunch</option>
                                    <option>Dinner</option>
                                </select>
                            </div>
                            <input type="hidden" id="userIdInput" name="user_id">
                            <input type="hidden" id="calorieInput" name="calorie">
                            <div class="input-field">
                                <label>Select Food Group</label>
                                <input type="text" name="food_group" class="selectbox" id="foodGroup"
                                    autocomplete="off">
                                </select>
                            </div>
                            <div class="input-field">
                                <label>Serving</label>
                                <input type="number" name="serving" placeholder="Serving" autocomplete="off" />
                            </div>
                            <div class="input-field input-field-btn btn-set--center">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </form>
                    </div>

                    <div class="tab-pane fade" id="activity" role="tabpanel" aria-labelledby="activity-tab">
                        <form method="post" action="{% url 'save_activity_data' %}">
                            {% csrf_token %}
                            <div class="input-field">
                                <label>Select Date</label>
                                <input type="date" id="date" name="date" max="2024-04-16" placeholder="Date"
                                    autocomplete="off" required>
                            </div>
                            <div class="input-field">
                                <label>Activity Name</label>
                                <select id="activity-name" name="activityName" class="selectbox" autocomplete="off"
                                    required>
                                    <option value="" selected disabled>Select Activity</option>

                                </select>
                            </div>
                            <div class="input-field">
                                <label>Activity Description</label>
                                <select id="activity-description" name="activityDescription" class="selectbox"
                                    autocomplete="off" required>
                                    <option value="" selected disabled>Select Activity Description for MET value
                                    </option>

                                </select>
                            </div>
                            <div class="input-field">
                                <label>MET Value</label>
                                <input type="text" id="met-value" name="metValue" value="" placeholder="MET Value"
                                    autocomplete="off" readonly>
                            </div>
                            <input type="hidden" id="userIdInput2" name="user_id">
                            <div class="input-field">
                                <label>Activity Duration(in minutes)</label>
                                <input type="number" name="duration" placeholder="Duration" autocomplete="off"
                                    required>
                            </div>
                            <div class="input-field input-field-btn btn-set--center">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

Users/templates/footer.html
{% load static %}
<!DOCTYPE html>
<html>
<body>
    <footer class="footer">
        <div class="container">
            <p>2024 LMD Consulting, LLC , All Rights Reserved</p>
        </div>
    </footer>
</body>
</html>

Users/templates/header.html
{% load static %}
<!DOCTYPE html>
<html>
<body>
    <header class="header">
        <div class="container">
            <div class="logo">
                <a href="{% url 'signup' %}">
                    <img src="{% static 'assets/img/logo.png' %}" alt="Calorie Tracker Logo">
                </a>
            </div>
        </div>  
    </header>
</body>
</html>

Users/templates/sign-up.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <link rel="icon" href="{% static 'assets/img/favicon.ico' %}" type="image/x-icon">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>Calorie Tracker Coding Assignment - Sign up</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700;800&display=swap" rel="stylesheet">
    <link href="{% static 'assets/css/global.css' %}" rel="stylesheet">
</head>
<body>
<div>
{% include "header.html" %} 
    <div class="mid-container">
        <div class="signup-container">
            <div class="white-card">
                <h1>Sign Up</h1>
                <div class="card-body">
                    <form method="POST" action="{% url 'signUpBtnClick' %}">
                        <div class="input-field">
                            <label for="id_name">Name</label>
                            <input type="text" name="name" id="id_name" placeholder="Name" autocomplete="off" required />
                        </div>
                        <div class="input-field">
                            <label for="id_weight">Weight(in Kilograms)</label>
                            <input type="text" name="weight" id="id_weight" placeholder="Weight" autocomplete="off"  required/>
                        </div>
                        <div class="input-field">
                            <label for="id_height">Height(in Centimeters)</label>
                            <input type="text" name="height" id="id_height" placeholder="Height"  autocomplete="off" required/>
                        </div>
                        <div class="input-field">
                            <label for="id_gender">Gender</label>
                            <select name="gender" id="id_gender" class="selectbox">
                                <option>Male</option>
                                <option>Female</option>
                            </select>
                        </div>
                        <div class="input-field">
                            <label for="id_age">Age(in Years)</label>
                            <input type="text" name="age" id="id_age" placeholder="Age" autocomplete="off" required />
                        </div>
                        <div class="input-field btn-set--right">
                            <div class="btn-set">
                                <button type="submit" class="btn-primary" >Sign Up</button>
                                <a class="btn-secondary" href="userList">User List</a>
    
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% include "footer.html" %} 
</div>
</body>
<script src="{% static 'assets/js/jquery.slim.min.js' %}"></script>
<script src="{% static 'assets/js/popper.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/custom.js' %}"></script>
</html>

Users/templates/user-list.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <link rel="icon" href="{% static 'assets/img/favicon.ico' %}" type="image/x-icon">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>Calorie Tracker Coding Assignment - User List</title>
    <style>
        .dropdown {
            position: relative;
            display: inline-block;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
            z-index: 1;
        }

        .dropdown-content a {
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
        }

        .dropdown-content a:hover {
            background-color: #f1f1f1;
        }

        .show {
            display: block;
        }
    </style>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700;800&display=swap"
        rel="stylesheet">
    <link href="{% static 'assets/css/global.css' %}" rel="stylesheet">
</head>

<body>
    <div>
        {% include "header.html" %} 
        <div class="mid-container">
            <div class="container">
                <div class="title-row">
                    <h1 class="title">User List</h1>
                </div>
                <div class="user-list">
                    <table class="dcf-table dcf-table-responsive dcf-table-bordered dcf-table-striped dcf-w-100%">
                        <thead>
                            <tr>
                                <th scope="col" class="name">Name</th>
                                <th scope="col" class="weight">Weight</th>
                                <th scope="col" class="height">Height</th>
                                <th scope="col" class="gender">Gender</th>
                                <th scope="col" class="age">Age</th>
                                <th scope="col" class="bmr">BMR</th>
                                <th scope="col" class="action">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for user in users reversed %}
                            <tr>
                                <th scope="row">{{ user.name }}</th>
                                <td data-label="Weight">{{ user.weight }}</td>
                                <td data-label="Height">{{ user.height }}</td>
                                <td data-label="Gender">{{ user.sex }}</td>
                                <td data-label="Age">{{ user.age }}</td>
                                <td>{{ user.bmr }}</td>
                                <td data-label="Action">
                                    <div class="btn-set">

                                        <a class="btn-secondary" href="view_user_data/{{user.id}}">View</a>


                                        <button class="btn-primary add-data-btn" data-toggle="modal"
                                            data-target="#addDataModal" data-userid="{{ user.id }}">Add Data</button>
                                        <form method="post" action="{% url 'delete_user' %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="user_id" value="{{ user.id }}">
                                            <button class="btn-secondary" type="submit">Delete</button>
                                        </form>

                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        {% include "footer.html" %} 
    </div>

    {% include "activity-food-popup.html" %} 

</body>
<script src="{% static 'assets/js/jquery.slim.min.js' %}"></script>
<script src="{% static 'assets/js/popper.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/custom.js' %}"></script>
<div id="foodJsonFilePath" data-path="{% static 'food-calories.json' %}"></div>
<script src="{% static 'assets/js/food-script.js' %}"></script>
<div id="activityJsonFilePath" data-path="{% static 'met-value.json' %}"></div>
<script src="{% static 'assets/js/activity-script.js' %}"></script>
<script>
    $(document).ready(function () {
        $('.add-data-btn').click(function () {
            var userId = $(this).data('userid');
            $('#userIdInput').val(userId);
        });
    });
</script>
<script>
    $(document).ready(function () {
        $('.add-data-btn').click(function () {
            var userId = $(this).data('userid');
            $('#userIdInput2').val(userId);
        });
    });
</script>
<script src="{% static 'assets/js/date-script.js' %}"></script>

</html>